### ISSUE TITLE
Get data loaders issues

### ISSUE THREAD

**Issue by JessicaAngulo** [BorjaRequena/step#3]
Hello, 
I was trying to train a new model using [00_model_training.ipynb](https://github.com/BorjaRequena/step/blob/master/nbs/tutorials/00_model_training.ipynb). I had issues getting the data loaders with `get_segmentation_dls`. 
I think there might be a bug where the function does not account for the number of changes (`n_change`). 
Am I doing something wrong?

**Comment by BorjaRequena** [comment]
Hi @jangulo4, thanks for showing interest in the project and spotting this issue!

It looks like the call to `load_dataset` in [this line](https://github.com/BorjaRequena/step/blob/175cfe3c6c626c6c8e28ffff23a37ca09aa32377/step/data.py#L354) is missing the key word argument `n_change`. Therefore, it is entirely ignoring the number of changes in the data set when generating the data loaders, always defaulting to `n_change=1`.

It is a rather simple fix, as it only requires the line to be `ds = load_dataset(n_change=n_change, bm=bm, **kwargs)`. Would you like to give it a go? If you open a PR, I can help you out with the [nbdev](https://nbdev.fast.ai/getting_started.html) nuances. Basically, it would be a matter of editing the corresponding notebook [00_data.ipynb](https://github.com/BorjaRequena/step/blob/175cfe3c6c626c6c8e28ffff23a37ca09aa32377/nbs/source/00_data.ipynb), and then running `nbdev_prepare`, which will take care of cleaning the notebook metadata, and updating the corresponding source file. Otherwise, I can do it myself tomorrow evening 😄

**Comment by JessicaAngulo** [comment]
Hello! Thank you very much for the fast reply! I did the PR. However, I did not update the nbdev nuances.

**Comment by BorjaRequena** [comment]
Resolved by #4 😄
